version: '3.8'
services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: kavach-dvwa
    ports:
      - "8085:80"
    restart: unless-stopped
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: kavach-juice-shop
    ports:
      - "4280:3000"
    restart: unless-stopped
