version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8085:80"
    restart: unless-stopped

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3001:3000"
    restart: unless-stopped
